Repository boostcampwm-2021/web22-boost-world-cup, pull requests merged in 2021-12, with the labels that each got.

#193 Backdrop 생성
  front/src/components/BackDrop/index.tsx
  front/src/components/MyWorldCupItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/components/WorldCupItem/index.tsx
  front/src/hooks/useInfiniteScroll.ts
Labels: 🍀 feature, 🐙 frontend, refactoring

#197 메인페이지 검색, 태그 필터링에 url 적용
  front/src/App.tsx
  front/src/components/Header/index.tsx
  front/src/pages/Main/index.tsx
Labels: 🐙 frontend, refactoring

#206 댓글 시간 수정 및 이미지 업로드 시 확장자 제거
  back/src/controller/worldcupController.ts
  front/src/components/CommentItem/index.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
Labels: 🐙 frontend

#201 refactor: 안쓰는 패키지 삭제 및 타입 관련 패키지 devDependencies로 이동 #200
  front/package-lock.json
  front/package.json
Labels: enhancement, 🐙 frontend

#205 월드컵 삭제시 태그도 삭제되도록 반영 및 UserInfo Form 수정
  back/src/services/keywordService.ts
  back/src/services/worldcupService.ts
  front/src/components/UserInfoForm/SingupButton/index.tsx
  front/src/components/UserInfoForm/UpdateButton/index.tsx
  front/src/components/UserInfoForm/index.tsx
Labels: 🍀 feature, 🐙 frontend, refactoring

#204 Pagination 컴포넌트에에 첫 페이지 / 마지막 페이지로 바로 이동할 수 있는 버튼 추가 #199
  front/src/components/Pagination/index.tsx
Labels: enhancement, 🐙 frontend

#198 Performance/issue#195
  README.md
  front/public/index.html
  front/src/App.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/ImgPreView/index.tsx
  front/src/components/MyWorldCupItem/index.tsx
  front/src/components/PrivateRoute/index.tsx
  front/src/components/PublicRoute/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/WorldCupItem/index.tsx
  front/src/components/index.ts
  front/src/constants/number.ts
  front/src/constants/route.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Loading/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/MyInfo/index.tsx
  front/src/pages/MyWorldcup/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/Profile/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/pages/Root/index.tsx
  front/src/pages/SignUp/index.tsx
  front/src/pages/index.ts
Labels: 🐙 frontend, performance

#211 performance: React.memo와 useCallback을 이용하여 불필요한 리렌더링 최소화 #209
  front/src/components/CommentList/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/Pagination/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/SearchBar/index.tsx
  front/src/components/TabBar/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/components/UserInfoForm/AgeSelector/index.tsx
  front/src/components/UserInfoForm/GenderSelector/index.tsx
  front/src/components/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/hooks/useInfiniteScroll.ts
  front/src/hooks/usePagination.ts
  front/src/hooks/useTabBar.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
Labels: 🐙 frontend, performance

#207 Enhancement/#164
  front/src/components/StoreBtns/index.tsx
Labels: enhancement, 🐙 frontend

#210 Enhancement/#163
  front/src/components/Image/index.tsx
  front/src/components/ImgPreView/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/utils/getImgURL.ts
Labels: enhancement, 🐙 frontend

#215 자신이 만든 월드컵이 아닌경우 수정&삭제 못하도록 수정
  back/src/controller/worldcupController.ts
  back/src/services/worldcupService.ts
  front/src/App.tsx
  front/src/pages/Edit/index.tsx
Labels: 🐳 backend, 🐙 frontend

#208 fix: 월드컵 생성페이지에서 이미지 변경이 비정상적으로 동작하는 오류 해결 #186
  front/src/hooks/useImgInfos.ts
  front/src/pages/Make/index.tsx
Labels: bug, 🐙 frontend

#214 Performance: 모달 코드 스플리팅 & 랭킹목록 divider 추가
  front/package-lock.json
  front/src/components/DeleteModal/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/MyWorldCupItem/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/DoughnutChart/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/types/Datas.ts
Labels: 🐙 frontend, refactoring, performance

#213 Enhancement/issue#165
  back/src/controller/bucketController.ts
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/pages/Edit/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/types/Datas.ts
  front/src/utils/validateImgType.ts
Labels: enhancement, 🐳 backend, 🐙 frontend
