Repository boostcampwm-2021/web22-boost-world-cup, pull requests merged in 2021-11, with the labels that each got.

#16 Mainpage UI 구현
  front/package.json
  front/src/components/Header/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/TagList/index.tsx
  front/src/components/WorldcupList/WorldCupItem.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  package-lock.json
Labels: 🐙 frontend

#11 백엔드 환경설정
  .gitignore
  back/.eslintrc
  back/ormconfig.json
  back/package-lock.json
  back/package.json
  back/src/api/index.ts
  back/src/api/userRouter.ts
  back/src/config/ormConfig.ts
  back/src/controller/UserController.ts
  back/src/controller/userController.ts
  back/src/entity/Candidate.ts
  back/src/entity/Comment.ts
  back/src/entity/Info.ts
  back/src/entity/Keyword.ts
  back/src/entity/User.ts
  back/src/entity/Worldcup.ts
  back/src/index.ts
  back/src/loaders/express.ts
  back/src/loaders/index.ts
  back/src/loaders/orm.ts
  back/src/routes.ts
  back/src/services/userService.ts
  back/tsconfig.json
Labels: 🐳 backend

#19 main page 구현
  front/package.json
  front/src/components/Header/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/SearchBar/index.tsx
  front/src/components/TagList/index.tsx
  front/src/components/WorldcupList/Loader/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/dummy.ts
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/utils/hooks.ts
Labels: 🍀 feature, 🐙 frontend

#18 Github & Kakao 로그인 구현
  .gitignore
  back/package.json
  back/src/@types/User.ts
  back/src/@types/index.d.ts
  back/src/api/authRouter.ts
  back/src/api/index.ts
  back/src/api/userRouter.ts
  back/src/config/githubStrategy.ts
  back/src/config/kakaoStrategy.ts
  back/src/config/orm.ts
  back/src/config/session.ts
  back/src/controller/authController.ts
  back/src/controller/userController.ts
  back/src/entity/User.ts
  back/src/loaders/express.ts
  back/src/loaders/orm.ts
  back/src/loaders/passport/githubPassport.ts
  back/src/loaders/passport/index.ts
  back/src/loaders/passport/kakaoPassport.ts
  back/src/services/authService.ts
  back/tsconfig.json
  front/package.json
  front/src/components/SocialLoginButton/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/SignUp/AgeSelector/index.tsx
  front/src/pages/SignUp/index.tsx
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#22 공통 헤더 props 수정
  front/src/components/Header/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
Labels: bug, 🐙 frontend

#28 월드컵 목록 서버에서 받아와서 출력
  back/src/api/index.ts
  back/src/api/worldcupRouter.ts
  back/src/controller/worldcupController.ts
  back/src/db/data.sql
  back/src/entity/Keyword.ts
  back/src/entity/Worldcup.ts
  back/src/loaders/express.ts
  back/src/services/worldcupService.ts
  back/src/tmp/worldcupRouter.ts
  front/src/components/Header/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/dummy.ts
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/utils/api/worldcups.ts
  front/src/utils/hooks/useInfinityScroll.ts
  package-lock.json
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#29 Make page
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/Make/reducer.ts
  front/src/types/Actions.ts
  front/src/types/Datas.ts
  front/src/types/States.ts
Labels: 🐳 backend, 🐙 frontend

#27 월드컵 목록, 태그 목록 api 구현
  README.md
  back/src/api/index.ts
  back/src/api/tagRouter.ts
  back/src/api/worldcupRouter.ts
  back/src/controller/tagController.ts
  back/src/controller/worldcupController.ts
  back/src/entity/Keyword.ts
  back/src/loaders/express.ts
  back/src/services/tagService.ts
  back/src/services/worldcupService.ts
Labels: 🍀 feature, 🐳 backend

#34 메인페이지 서버에서 데이터 fetch
  back/src/controller/worldcupController.ts
  back/src/services/worldcupService.ts
  back/src/tmp/worldcupRouter.ts
  front/src/components/Header/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/utils/api/keywords.ts
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#39 게임 초기화 화면
  back/src/api/index.ts
  back/src/controller/worldcupController.ts
  back/src/services/worldcupService.ts
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/RoundSelector/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/images/select.png
  front/src/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Root/index.tsx
  front/src/pages/SignUp/AgeSelector/index.tsx
  front/src/pages/SignUp/GenderSelector/index.tsx
  front/src/pages/SignUp/SingupButton/index.tsx
  front/src/pages/SignUp/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/pages/index.ts
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#42 키워드 및 태그 검색 api 구현
  back/src/controller/worldcupController.ts
  back/src/services/worldcupService.ts
Labels: 🐳 backend

#44 게임 페이지
  back/src/api/gameRouter.ts
  back/src/api/index.ts
  back/src/config/cookie.ts
  back/src/controller/gameController.ts
  back/src/controller/worldcupController.ts
  back/src/loaders/express.ts
  back/src/services/candidateService.ts
  back/src/services/worldcupService.ts
  front/src/commons/style/theme.ts
  front/src/pages/Initialize/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/game.ts
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#43 월드컵 생성 페이지 update / 클라우드 플랫폼 ncloud로 변경
  cloud-functions/index.js
  cloud-functions/package-lock.json
  cloud-functions/package.json
  front/src/components/ImgInput/index.tsx
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTablePagination/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakePageTabBar/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/pages/Make/index.tsx
  front/src/types/Datas.ts
Labels: 🐳 backend, 🐙 frontend

#46 무한 스크롤, 태그 필터링, 검색 필터링
  .gitignore
  back/src/controller/worldcupController.ts
  back/src/loaders/express.ts
  back/src/services/worldcupService.ts
  front/package-lock.json
  front/src/components/Keywords/index.tsx
  front/src/components/WorldcupList/Loader/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/utils/api/worldcups.ts
  front/src/utils/hooks/useInfinityScroll.ts
  package-lock.json
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#50 월드컵 생성 페이지 update / 클라우드 플랫폼 ncloud로 변경
  cloud-functions/index.js
  cloud-functions/package-lock.json
  cloud-functions/package.json
  front/src/components/ImgInput/index.tsx
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTablePagination/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakePageTabBar/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/pages/Make/index.tsx
  front/src/types/Datas.ts
Labels: 🐳 backend, 🐙 frontend

#56 Feat/worldcup2
  README.md
  back/src/api/gameRouter.ts
  back/src/controller/gameController.ts
  back/src/controller/worldcupController.ts
  back/src/loaders/express.ts
  back/src/services/candidateService.ts
  front/package-lock.json
  front/package.json
  front/src/pages/Initialize/index.tsx
  front/src/pages/Worldcup/gameover.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/game.ts
  front/src/utils/crypto/index.ts
Labels: bug, 🐙 frontend

#51 Feature/makepage
  back/package.json
  back/src/api/bucketRouter.ts
  back/src/api/candidateRouter.ts
  back/src/api/index.ts
  back/src/config/s3.ts
  back/src/controller/bucketController.ts
  back/src/controller/candidateController.ts
  back/src/entity/Candidate.ts
  back/src/services/candidateService.ts
  cloud-functions/index.js
  front/src/pages/Make/index.tsx
Labels: 🐳 backend, 🐙 frontend

#55 전역 유저 상태관리, 카카오톡 공유 기능
  back/package-lock.json
  back/package.json
  back/src/api/authRouter.ts
  back/src/controller/authController.ts
  front/src/components/Header/index.tsx
  front/src/components/Modal/index.tsx
  front/src/components/ShareModal/KakaoButton/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/images/kakao.png
  front/src/pages/Initialize/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/react-app-env.d.ts
  front/src/utils/api/auth.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#63 Make 페이지
  back/src/controller/worldcupController.ts
  back/src/services/candidateService.ts
  back/src/services/tagService.ts
  back/src/services/worldcupService.ts
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/Make/reducer.ts
  front/src/types/Actions.ts
  front/src/types/States.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#64 게임페이지
  back/package-lock.json
  back/src/api/gameRouter.ts
  back/src/config/cookie.ts
  back/src/controller/authController.ts
  back/src/controller/gameController.ts
  back/src/index.ts
  front/src/pages/Initialize/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Worldcup/gameover.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/utils/api/game.ts
Labels: 🐙 frontend

#67 Enhancement/issue#66
  back/src/controller/bucketController.ts
  cloud-functions/index.js
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/Make/reducer.ts
  front/src/types/Datas.ts
Labels: enhancement, 🐳 backend, 🐙 frontend

#70 배포시 에러나는 부분 수정
  back/package-lock.json
  back/src/loaders/express.ts
  front/package-lock.json
  front/src/pages/Login/index.tsx
Labels: bug

#71 feat : NotFound Page 구현
  back/src/config/orm.ts
  back/src/loaders/express.ts
  back/tsconfig.json
  front/src/App.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/index.ts
Labels: 🍀 feature, 🐙 frontend

#69 Refactoring/issue#68
  back/src/controller/candidateController.ts
  front/.eslintrc.js
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakePageTabBar/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/hooks/useApiRequest.ts
  front/src/pages/Make/index.tsx
  front/src/pages/Make/reducer.ts
  front/src/pages/Make/store.tsx
  front/src/pages/Make/view.tsx
  front/src/utils/api/image.ts
  front/src/utils/api/worldcups.ts
Labels: 🐙 frontend, refactoring

#73 db entity 변경
  back/src/entity/User.ts
  back/src/entity/Worldcup.ts
Labels: 🐳 backend

#82 게임 api 구현 및 댓글 작성 및 조회
  back/src/api/commentRouter.ts
  back/src/api/index.ts
  back/src/api/rankingRouter.ts
  back/src/controller/commentController.ts
  back/src/controller/rankingController.ts
  back/src/entity/Candidate.ts
  back/src/loaders/express.ts
  back/src/services/candidateService.ts
  back/src/services/commentService.ts
  back/src/services/infoService.ts
  back/src/services/worldcupService.ts
  back/src/types/User.ts
  back/src/types/common.ts
  back/src/types/index.d.ts
  back/tsconfig.json
  front/src/components/Comment/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/comment.ts
  front/src/utils/api/ranking.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#85 Refactoring/issue83
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTablePagination/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/components/index.ts
  front/src/hooks/index.ts
  front/src/hooks/useImgInfos.ts
  front/src/hooks/usePagination.ts
  front/src/hooks/useTabBar.ts
  front/src/hooks/useUploadImg.ts
  front/src/hooks/useUploadState.ts
  front/src/hooks/useWorldcupForm.ts
  front/src/pages/Make/index.tsx
  front/src/pages/Make/reducer.ts
  front/src/pages/Make/store.tsx
  front/src/pages/Make/view.tsx
  front/src/types/Datas.ts
  front/src/utils/getUUID.ts
Labels: 🐙 frontend, refactoring

#87 [Bug] worldcupList merge bug 해결
  front/package-lock.json
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/ShareModal/KakaoButton/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/components/index.ts
  front/src/pages/Main/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/pages/index.ts
Labels: bug

#84 Main page 공유모달, 필터링 분기 + Ranking page전체 통계 ui
  back/src/loaders/express.ts
  front/package-lock.json
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/ShareModal/KakaoButton/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/components/index.ts
  front/src/pages/Main/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/pages/index.ts
Labels: 🍀 feature, 🐙 frontend

#97 ranking page 전체랭킹, 세부랭킹(연령별)
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/components/SearchBar/index.tsx
  front/src/components/TabBar/index.tsx
  front/src/components/index.ts
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/Ranking/index.tsx
Labels: 🐙 frontend

#93 댓글 작성 구현 및 css 변경
  back/src/api/commentRouter.ts
  back/src/controller/commentController.ts
  back/src/loaders/express.ts
  back/src/services/commentService.ts
  back/src/services/infoService.ts
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/comment.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Loader/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/SignUp/AgeSelector/index.tsx
  front/src/pages/SignUp/GenderSelector/index.tsx
  front/src/pages/SignUp/SingupButton/index.tsx
  front/src/pages/SignUp/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/comment.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#94 Enhancement/issue76 + Feature/issue89
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/hooks/useImgInfos.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/index.ts
  front/src/utils/api/candidate.ts
  front/src/utils/api/image.ts
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐙 frontend

#95 login 및 user정보 전역상태관리 및 회원탈퇴 기능 구현
  back/src/api/authRouter.ts
  back/src/api/index.ts
  back/src/api/userRouter.ts
  back/src/controller/authController.ts
  back/src/controller/userController.ts
  back/src/services/authService.ts
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/Header/HeaderModal/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/MyInfo/index.tsx
  front/src/pages/index.ts
  front/src/utils/api/auth.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#104 댓글 구현 및 css 보완
  back/src/api/commentRouter.ts
  back/src/api/index.ts
  back/src/api/worldcupRouter.ts
  back/src/controller/commentController.ts
  back/src/controller/worldcupController.ts
  front/src/commons/style/theme.ts
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/comment.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/SearchBar/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/components/index.ts
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/pages/Worldcup/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/comment.ts
Labels: enhancement, 🐙 frontend

#105 랭킹페이지 구현
  back/src/api/rankingRouter.ts
  back/src/controller/rankingController.ts
  back/src/services/candidateService.ts
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/components/TabBar/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/ranking.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#106 유저정보 수정하기 기능 구현
  back/src/api/authRouter.ts
  back/src/controller/authController.ts
  back/src/services/authService.ts
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/UserInfoForm/AgeSelector/index.tsx
  front/src/components/UserInfoForm/GenderSelector/index.tsx
  front/src/components/UserInfoForm/SingupButton/index.tsx
  front/src/components/UserInfoForm/UpdateButton/index.tsx
  front/src/components/UserInfoForm/index.tsx
  front/src/pages/Profile/index.tsx
  front/src/pages/SignUp/index.tsx
  front/src/pages/index.ts
  front/src/utils/api/auth.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#102 Feature/issue96
  back/src/api/candidateRouter.ts
  back/src/api/worldcupRouter.ts
  back/src/controller/candidateController.ts
  back/src/controller/worldcupController.ts
  back/src/services/candidateService.ts
  back/src/services/worldcupService.ts
Labels: 🍀 feature, 🐳 backend

#108 Refactoring/issue#103
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/hooks/useApiRequest.ts
  front/src/hooks/useUploadImg.ts
  front/src/pages/Edit/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/worldcups.ts
Labels: 🐙 frontend, refactoring

#113 Refactoring/issue#112 + Enhancement/issue#110
  back/src/controller/candidateController.ts
  back/src/controller/worldcupController.ts
  back/src/loaders/express.ts
  back/src/services/candidateService.ts
  back/src/services/infoService.ts
  back/src/services/tagService.ts
  back/src/services/worldcupService.ts
  back/src/utils/cloud.ts
  front/src/pages/Edit/index.tsx
Labels: enhancement, 🐳 backend, 🐙 frontend, refactoring

#116 ranking page 보완 작업
  back/src/services/candidateService.ts
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/types/Datas.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#117 ranking page 코드 수정
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/types/Datas.ts
Labels: 🍀 feature, 🐙 frontend, refactoring

#119 Refactoring/issue#118
  front/src/components/ImgTable/index.tsx
  front/src/components/Pagination/index.tsx
  front/src/hooks/index.ts
  front/src/hooks/usePagination.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Make/index.tsx
  front/src/utils/api/worldcups.ts
Labels: 🐙 frontend, refactoring

#124 내가 만든 월드컵 목록 보여주기, 내가 만든 월드컵 삭제하기 기능 구현
  back/src/api/worldcupRouter.ts
  back/src/controller/worldcupController.ts
  back/src/entity/Candidate.ts
  back/src/entity/Comment.ts
  back/src/entity/Info.ts
  back/src/entity/Worldcup.ts
  back/src/services/worldcupService.ts
  front/src/components/DeleteModal/Button/index.tsx
  front/src/components/DeleteModal/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐳 backend, 🐙 frontend

#127 Fix & 해시태그
  README.md
  back/package-lock.json
  back/package.json
  back/src/entity/Info.ts
  back/src/loaders/express.ts
  back/src/services/infoService.ts
  back/src/types/common.ts
  front/src/components/Comment/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/images/versus.png
  front/src/images/vs.png
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
Labels: enhancement, 🍀 feature

#125 Refactoring/issue#122
  back/src/controller/worldcupController.ts
  front/.eslintrc.js
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/hooks/index.ts
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/Main/index.tsx
  front/src/types/Datas.ts
  front/src/utils/api/comment.ts
  front/src/utils/api/worldcups.ts
Labels: 🍀 feature, 🐙 frontend, refactoring

#129 [refactor] 백엔드 데이터담는 객체 생성
  back/src/config/orm.ts
  back/src/controller/worldcupController.ts
  back/src/services/worldcupService.ts
  back/src/utils/ApiResult.ts
Labels: 🐳 backend, refactoring

#145 doughnut chart 애니메이션 기능 수정
  front/src/components/RankingModal/DoughnutChart/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/types/Datas.ts
Labels: bug, 🐙 frontend

#134 Mainpage 버그 수정, 기능구현 + Rankingpage 페이지네이션
  back/package-lock.json
  back/src/controller/rankingController.ts
  back/src/controller/tagController.ts
  back/src/services/candidateService.ts
  back/src/services/tagService.ts
  front/public/favicon.ico
  front/public/index.html
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/utils/api/keywords.ts
  front/src/utils/api/ranking.ts
Labels: bug, enhancement, 🐳 backend, 🐙 frontend

#136 오류 수정 및 refactor
  back/src/controller/authController.ts
  back/src/controller/worldcupController.ts
  back/src/entity/Comment.ts
  back/src/entity/User.ts
  back/src/entity/Worldcup.ts
  back/src/services/authService.ts
  back/src/services/worldcupService.ts
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/MyWorldcup/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/utils/api/worldcups.ts
Labels: bug, refactoring

#135 로그인 시 페이지 유지
  back/src/api/authRouter.ts
  back/src/controller/authController.ts
  front/src/components/Header/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Ranking/index.tsx
Labels: enhancement

#142 Refactoring/issue#141
  front/src/hooks/index.ts
  front/src/hooks/useSearchBar.ts
  front/src/pages/Main/index.tsx
  front/src/pages/MyWorldcup/index.tsx
Labels: 🐙 frontend, refactoring

#144 Refactoring/issue#143
  back/src/controller/authController.ts
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/commons/constants/route.ts
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/comment.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/Header/index.tsx
  front/src/components/Image/index.tsx
  front/src/components/PrivateRoute/index.tsx
  front/src/components/PublicRoute/index.tsx
  front/src/components/UserInfoForm/UpdateButton/index.tsx
  front/src/components/UserInfoForm/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/components/index.ts
  front/src/hooks/index.ts
  front/src/hooks/useLoginCheck.ts
  front/src/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Loading/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/MyWorldcup/index.tsx
  front/src/pages/Profile/index.tsx
  front/src/recoil/atom.ts
  front/src/stores/index.tsx
  front/src/stores/userStore/index.tsx
  front/src/stores/userStore/reducer.ts
  front/src/types/Actions.ts
  front/src/types/Datas.ts
  front/src/types/Reducer.ts
  front/src/types/States.ts
  front/src/utils/api/auth.ts
Labels: 🐙 frontend, refactoring

#151 Make Page 디자인 수정 및 버그 수정
  README.md
  front/src/commons/style/theme.ts
  front/src/components/ImgInput/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/Pagination/index.tsx
  front/src/components/PrivateRoute/index.tsx
  front/src/components/RankingModal/BarChart/index.tsx
  front/src/components/RankingModal/DoughnutChart/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/components/SearchBar/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/TabBar/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Make/index.tsx
Labels: enhancement, 🐙 frontend

#155 Refactoring/issue#154
  back/src/controller/authController.ts
  back/src/controller/bucketController.ts
  back/src/controller/candidateController.ts
  back/src/controller/gameController.ts
  back/src/controller/rankingController.ts
  back/src/controller/tagController.ts
  back/src/controller/worldcupController.ts
  back/src/services/commentService.ts
  front/src/commons/constants/number.ts
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/comment.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/DeleteModal/Button/index.tsx
  front/src/components/DeleteModal/index.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RoundSelector/index.tsx
  front/src/components/ShareModal/KakaoButton/index.tsx
  front/src/components/ShareModal/index.tsx
  front/src/components/UserInfoForm/AgeSelector/index.tsx
  front/src/components/UserInfoForm/GenderSelector/index.tsx
  front/src/components/UserInfoForm/SingupButton/index.tsx
  front/src/components/UserInfoForm/UpdateButton/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/hooks/useApiRequest.ts
  front/src/hooks/useInfiniteScroll.ts
  front/src/pages/Game/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Login/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Ranking/index.tsx
  front/src/utils/api/auth.ts
  front/src/utils/api/candidate.ts
  front/src/utils/api/comment.ts
  front/src/utils/api/game.ts
  front/src/utils/api/keywords.ts
  front/src/utils/api/ranking.ts
  front/src/utils/api/worldcups.ts
Labels: 🐳 backend, 🐙 frontend, refactoring

#157 Enhancement/make
  front/src/components/ImgInput/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/TextInput/index.tsx
  front/src/hooks/useWorldcupForm.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Loading/index.tsx
  front/src/pages/Make/index.tsx
Labels: enhancement, 🐙 frontend

#159 Refactoring/issue#156
  back/src/entity/Candidate.ts
  back/src/services/candidateService.ts
  back/src/services/worldcupService.ts
  front/src/components/Image/index.tsx
  front/src/components/RankingList/RankingItem/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/types/Datas.ts
  front/src/utils/getImgURL.ts
Labels: 🐳 backend, 🐙 frontend, refactoring

#184 useModal custom hook & modal css수정
  back/src/entity/Keyword.ts
  front/src/components/DeleteModal/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/RankingModal/index.tsx
  front/src/components/WorldcupList/MyWorldCupItem/index.tsx
  front/src/components/WorldcupList/WorldCupItem/index.tsx
  front/src/hooks/index.ts
  front/src/hooks/useModal.ts
  front/src/pages/Main/index.tsx
Labels: bug, 🐙 frontend, refactoring

#176 refactor: 불필요한 else 제거 #174
  back/src/controller/worldcupController.ts
  front/src/components/Header/index.tsx
Labels: refactoring

#183 Refactoring/issue#175, #182
  front/src/components/Comment/index.tsx
  front/src/components/CommentList/comment.tsx
  front/src/components/CommentList/index.tsx
  front/src/components/DeleteModal/index.tsx
  front/src/components/Header/HeaderModal/index.tsx
  front/src/components/ImgPreView/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTable/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/KeywordInput/index.tsx
  front/src/components/Keywords/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/RankingList/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/UserInfoForm/SingupButton/index.tsx
  front/src/components/UserInfoForm/UpdateButton/index.tsx
  front/src/hooks/index.ts
  front/src/hooks/useApiRequest.ts
  front/src/hooks/useImgInfos.ts
  front/src/hooks/useInfiniteScroll.ts
  front/src/hooks/useLoginCheck.ts
  front/src/hooks/usePagination.ts
  front/src/hooks/useThrottle.ts
  front/src/hooks/useUploadImg.ts
  front/src/hooks/useUploadState.ts
  front/src/hooks/useWorldcupForm.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/types/Actions.ts
  front/src/types/States.ts
Labels: 🐙 frontend, refactoring

#189 리액트 컴포넌트 합성을 이용한 리팩토링 및 뷰 수정
  front/src/components/Header/index.tsx
  front/src/components/ImgInput/index.tsx
  front/src/components/ImgInputs/AddAdditionalImgs/index.tsx
  front/src/components/ImgInputs/AddImgs/index.tsx
  front/src/components/ImgInputs/ChangeImg/index.tsx
  front/src/components/ImgPreViewList/index.tsx
  front/src/components/ImgTableRow/index.tsx
  front/src/components/MakeWorldcupForm/index.tsx
  front/src/components/MyWorldCupItem/index.tsx
  front/src/components/StoreBtns/index.tsx
  front/src/components/WorldCupItem/index.tsx
  front/src/components/WorldcupList/index.tsx
  front/src/components/index.ts
  front/src/pages/Edit/index.tsx
  front/src/pages/Game/index.tsx
  front/src/pages/Gameover/index.tsx
  front/src/pages/Initialize/index.tsx
  front/src/pages/Leave/index.tsx
  front/src/pages/Main/index.tsx
  front/src/pages/Make/index.tsx
  front/src/pages/MyInfo/index.tsx
  front/src/pages/MyWorldcup/index.tsx
  front/src/pages/NotFound/index.tsx
  front/src/pages/Profile/index.tsx
  front/src/pages/Ranking/index.tsx
Labels: 🐙 frontend, refactoring
